/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hgadkari' at '8/26/16 10:11 AM' with Gradle 2.14.1
 *
 * @author hgadkari, @date 8/26/16 10:11 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
