/*import org.junit.Test;
import static org.junit.Assert.*;*/

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hgadkari' at '8/26/16 10:11 AM' with Gradle 2.14.1
 *
 * @author hgadkari, @date 8/26/16 10:11 AM
 */
public class LibraryTest {
  //  @Test
	public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
